### ISSUE TITLE
Copying event listeners and adding a "done" callback

### ISSUE THREAD

**Issue by MaxJohnson** [createlogic/InlineSVG#1]
Love this plugin and want to contribute! Currently, any events attached to the <img> tag that is being replaced are lost. In addition, there is no callback when the swap is completed. Sooo, I submit this additional code for your inspection and hopefully approval:
starting at line 31
....
                // Remove any invalid XML tags as per http://validator.w3.org
                $svg = $svg.removeAttr('xmlns:a');

```
    // NEW Copy any event listeners over 
    $.each($._data($img.get(0), 'events'), function() {
        // iterate registered handler of original
        $.each(this, function() {
            $svg.bind(this.type, this.handler);
        });
    });

            // Replace image with new SVG
            $img.replaceWith($svg);

    // NEW Pass along the "done" event from the "get"
    $svg.trigger("done", [$svg]);
```

.....

**Comment by createlogic** [comment]
Thanks I would look into it and update the repo.

Regards,
Bilal

**Comment by unclechu** [comment]
@MaxJohnson now it has options arguments with done-callbacks for after all elements replaced and for each replaced elements, does it solves your issue?

**Comment by MaxJohnson** [comment]
Thanks @unclechu ! This is a great solution for callbacks.
