### ISSUE TITLE
Events are not cloned to svg from img

### ISSUE THREAD

**Issue by MaxJohnson** [createlogic/InlineSVG#7]
When the image object gets replaced with the svg, any event listeners (eg. 'click', 'keydown', etc) that had been on the original image object are lost.

That could probably be solved with a one-liner before the swap:
$img.copyEventsTo($svg);

Untested though...

**Comment by unclechu** [comment]
@MaxJohnson what it `copyEventsTo`? It's some sort of jQuery method? There's no method like this in jQuery prototype.

**Comment by unclechu** [comment]
@MaxJohnson in v2 there's `beforeReplace` callback, you can do what you want to by this callback.
See for API here: https://github.com/createlogic/InlineSVG/blob/master/jquery.inlinesvg.js

For example: you can use this plugin:
http://www.armin-pfaeffle.de/blog/2014/08/jquery-copy-events-from-one-element-to-another/
And do something like this:

``` javascript
$('img[src$=".svg"]').inlineSVG({
  beforeReplace: function ($img, $svg, next) {
    $img.copyEvents($svg); // copy events from $img to $svg
    next(); // can be asynchronous
  }
});
```

Does it solve your issue?
